services:
  - type: web
    name: efootball-tournament-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: "@eFootball_Tournamentsbot"
      - key: ADMIN_ID
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: PAYMENT_GATEWAY_KEY
        sync: false
      - key: PAYMENT_GATEWAY_SECRET
        sync: false
      - key: WEBHOOK_URL
        generateValue: true
        type: web_service_url
      - key: PORT
        value: "10000"
    healthCheckPath: "/health"